CREATE TABLE "scout" (
	"id"	TEXT NOT NULL,
	"first_name"	TEXT NOT NULL,
	"last_name"	TEXT NOT NULL,
	"birth_year"	INTEGER NOT NULL,
	"email_1"	TEXT NOT NULL,
	"phone_number_1"	TEXT NOT NULL,
	"troop_name"	TEXT NOT NULL,
	"troop_number"	INTEGER NOT NULL,
	"troop_url"	TEXT NOT NULL,
	"country"	TEXT NOT NULL,
	"state"	TEXT NOT NULL,
	"city"	TEXT NOT NULL,
	"rank"	TEXT NOT NULL,
	"been_to_jubilee"	TEXT NOT NULL,
	"can_set_fire"	TEXT NOT NULL,
	"can_carve_wood"	TEXT NOT NULL,
	"can_train_others"	TEXT NOT NULL,
	"can_make_sausage"	TEXT NOT NULL,
	"can_lead_campfire"	TEXT NOT NULL,
	"can_first_aid"	TEXT NOT NULL,
	"can_cook"	TEXT NOT NULL,
	PRIMARY KEY("id")
)
